spring.application.name=CRUDSpringBootDemo

#url tells Spring Boot where the database is located
#jdbc -> Java Database Connectivity URL format
spring.datasource.url=jdbc:postgresql://localhost:5432/student_crud_db
spring.datasource.username=lokkhiii
spring.datasource.password=7585

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.hibernate.ddl-auto
#    - how Hibernate handles database table structure with update
#    - Hibernate checks the  entity class and tries to update the table structure accordingly
#    - existing data is usually not deleted with update
#ddl-auto values:
#    - none : Hibernate will not manage the table structure
#    - validate: Hibernate only checks whether the table matches the entity
#    - update: Hibernate updates the table structure based on the entity
#    - create: Drops old tables and creates fresh tables every time the app starts
#    - create-drop: Create tables when the app starts and drops them when the app stops

#spring.jpa.show-sql=true
#    - this tells Hibernate to print SQL queries in the console

#spring.jpa.properties.hibernate.format_sql=true
#    - this formates SQl queries properly in the console
#    - without formatting, the SQlL query may appear in one long line
#    - with formatting, it becomes more readable
